version: 2.1

jobs:
  build_req_install:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: python:3.6 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Just echo comnmand
          command: echo "hello world" # run the `echo` command
      - run:
          name: Install requirements
          command: pip install -r requirements.txt