version: 2.1

jobs:
  build_install:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
          
  build_lints:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Black check
          command: |
            pip install black
            black --check database/ image_processing/ gui/ indexing/ video_processing/ run.py
      - run:
          name: Install requirements
          command: |
            pip install flake8
            flake8 database/ image_processing/ indexing/ gui/ run.py

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_install
      - build_lints